//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campaign()
        {
            this.CampaignMonths = new HashSet<CampaignMonth>();
            this.CampaignTrades = new HashSet<CampaignTrade>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Objective { get; set; }
        public int CampaignTypeID { get; set; }
        public int CampaignLeadID { get; set; }
        public int StatusID { get; set; }
        public int EmailSystemID { get; set; }
        public Nullable<int> CampaignPlanID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        [AllowHtml]
        public string CampaignMarket { get; set; }
        [AllowHtml]
        public string CampaignProducts { get; set; }
        [AllowHtml]
        public string SuccessMetric { get; set; }
        public string AccountSize { get; set; }
        public string ContactPriority { get; set; }
        [AllowHtml]
        public string Notes { get; set; }
        public string CampaignProjectManager { get; set; }
        [AllowHtml]
        public string Email { get; set; }
        public Nullable<int> Email_Deliveries { get; set; }
        public Nullable<int> Website_Sessions { get; set; }
        public Nullable<int> Transactions { get; set; }
        public Nullable<int> Email_Recipients { get; set; }
        public Nullable<decimal> Open_Rate { get; set; }
        public Nullable<decimal> Click_Rate { get; set; }
        public Nullable<decimal> Bounce_Rate { get; set; }
        public Nullable<decimal> Conversion_Rate { get; set; }
        [AllowHtml]
        public string LandingPage { get; set; }
        public string LandingUrl { get; set; }
        public string USGraphWeeks { get; set; }
        public string USGraphWeekRevenue { get; set; }
        public string USGraphWeekUnits { get; set; }
        public string CAGraphWeekUnits { get; set; }
        public string CAGraphWeekRevenue { get; set; }
        public string CAGraphWeeks { get; set; }
        public string Email_Status { get; set; }
    
        public virtual CampaignType CampaignType { get; set; }
        public virtual CampaignLead CampaignLead { get; set; }
        public virtual CampaignPlan CampaignPlan { get; set; }
        public virtual EmailSystem EmailSystem { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignMonth> CampaignMonths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignTrade> CampaignTrades { get; set; }
    }
}
