//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketingEntities : DbContext
    {
        public MarketingEntities()
            : base("name=MarketingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CampaignLead> CampaignLeads { get; set; }
        public virtual DbSet<CampaignMonth> CampaignMonths { get; set; }
        public virtual DbSet<CampaignOwner> CampaignOwners { get; set; }
        public virtual DbSet<CampaignTrade> CampaignTrades { get; set; }
        public virtual DbSet<CampaignType> CampaignTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<EmailSystem> EmailSystems { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Trade> Trades { get; set; }
        public virtual DbSet<CampaignPlan> CampaignPlans { get; set; }
        public virtual DbSet<CampaignMarket> CampaignMarkets { get; set; }
        public virtual DbSet<AccountSize> AccountSizes { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<vCampaignTypeMonth> vCampaignTypeMonths { get; set; }
        public virtual DbSet<vCampaignTradeMonth> vCampaignTradeMonths { get; set; }
        public virtual DbSet<EmailStatu> EmailStatus { get; set; }
    }
}
