//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class TemplateC
    {
        public int ID { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public string HeadLine { get; set; }
        public string SubHeadLine { get; set; }
        public string KeyBannerImage { get; set; }
        [AllowHtml]
        public string IntroductionMessage { get; set; }
        public string CTAText { get; set; }
        public string CTALink { get; set; }
        public string SecondaryCaption { get; set; }
        public string Column1Image { get; set; }
        public string Column1Title { get; set; }
        public string Column1Message { get; set; }
        public string Column1CTAText { get; set; }
        public string Column1CTALink { get; set; }
        public string Column2Image { get; set; }
        public string Column2Title { get; set; }
        public string Column2Message { get; set; }
        public string Column2CTAText { get; set; }
        public string Column2CTALink { get; set; }
        public string Tags { get; set; }
        public string HeadLine1 { get; set; }
        public string SubHeadLine1 { get; set; }
        public string KeyBannerImage1 { get; set; }
        [AllowHtml]
        public string IntroductionMessage1 { get; set; }
        public string CTAText1 { get; set; }
        public string CTALink1 { get; set; }
        public string SecondaryCaption1 { get; set; }
        public string Column1Image1 { get; set; }
        public string Column1Title1 { get; set; }
        public string Column1Message1 { get; set; }
        public string Column1CTAText1 { get; set; }
        public string Column1CTALink1 { get; set; }
        public string Column2Image1 { get; set; }
        public string Column2Title1 { get; set; }
        public string Column2Message1 { get; set; }
        public string Column2CTAText1 { get; set; }
        public string Column2CTALink1 { get; set; }
    
        public virtual Campaign Campaign { get; set; }
    }
}
